# Generated by Django 5.0 on 2024-05-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_outlet', '0002_movie_is_bestselling_movie_main_act_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
