# Generated by Django 5.0 on 2024-05-10 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_outlet', '0004_actor_alter_movie_main_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='main_act',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='video_outlet.actor'),
        ),
    ]
