# Generated by Django 5.0 on 2024-05-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_outlet', '0006_address_actor_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='streetstreet',
            new_name='street',
        ),
    ]
