# Generated by Django 5.0 on 2024-05-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_outlet', '0008_language_alter_address_options_movie_translated_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='translated_to',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
