# Generated by Django 5.0 on 2024-05-12 07:23

import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_outlet', '0011_alter_movie_translated_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='translated_to',
            field=models.ManyToManyField(default=django.db.models.query.QuerySet.none, to='video_outlet.language'),
        ),
    ]
